src/com/ft/jenkins/Cluster.groovy
src/com/ft/jenkins/DeploymentUtils.groovy
src/com/ft/jenkins/DeploymentUtilsConstants.groovy
src/com/ft/jenkins/Environment.groovy
src/com/ft/jenkins/EnvsRegistry.groovy
src/com/ft/jenkins/ParamUtils.groovy
src/com/ft/jenkins/aws/AwsUtils.groovy
src/com/ft/jenkins/docker/DockerUtils.groovy
src/com/ft/jenkins/slack/SlackUtils.groovy
vars/devBuildAndDeploy.groovy
vars/entryPointForReleaseAndDev.groovy
vars/installHelmChart.groovy
vars/releaseBuildAndDeploy.groovy

Implemented installation from a Helm repository
Implemented deploying through a single generic job.

Helm repo integration

---

.circleci/config.yml
pom.xml
test-src/com/ft/jenkins/git/GitUtilsTest.groovy

Latest run on circleci https://circleci.com/gh/Financial-Times/k8s-pipeline-library/4

Maven build & circle ci integration

---

src/com/ft/jenkins/DeploymentUtils.groovy
src/com/ft/jenkins/EnvsRegistry.groovy
vars/pacEntryPointForJenkinsfile.groovy

Created an environment for prod pac cluster
Not setting the env and region as a helm value coz we are using a wildcard host in the helm config

PAC cluster changes

---

src/com/ft/jenkins/EnvsRegistry.groovy

- to make the helm version shorter

Renamed environment in content-test.

---

src/com/ft/jenkins/DeploymentUtils.groovy

Implemented searching first for region specific for an environment specific configuration.

Handle region specific app config

---

vars/diffBetweenEnvs.groovy

Add default behavior for checkboxes.
Configured the display name.

Diff and sync small improvements

---

pom.xml
src/com/ft/jenkins/DeploymentUtils.groovy
src/com/ft/jenkins/Environment.groovy
src/com/ft/jenkins/EnvsRegistry.groovy
test-src/com/ft/jenkins/DeploymentUtilTest.java

Updated Junit to latest version.

Implemented exposing the cluster urls of the environment.

---

vars/pacEntryPointForJenkinsfile.groovy

I adjusted the entry point to match the names in EnvsRegistry.

Adjusted the PAC entry points

---

src/com/ft/jenkins/provision/ProvisionConstants.groovy
vars/updateCluster.groovy

I tested it all still works in https://upp-k8s-jenkins.in.ft.com/job/k8s-deployment/job/utils/job/update-cluster/107/

Move provisioner repo + add reason in description 

---

src/com/ft/jenkins/DeploymentUtils.groovy

internal load balancers take a long time to create.

Increased helm install timeout to 20 mins.

---

vars/installHelmChart.groovy

Fixes #53: Fixed build description to use the selected cluster name.

Jenkins pipeline fixes.

---

.gitignore
vars/updateDexConfigs.groovy

- checkout the dex config
- parse the secrets we get as input
- run a helm dry-run to replace the secrets in the template
- take the filled in template and give it to an util to encode the secrets
- apply the update for the secret using helm

Update dex configs

---

vars/genericEntryPointForJenkinsfile.groovy

Don't allow deploy-on-push to upper envs

---

pom.xml
src/com/ft/jenkins/DeploymentUtils.groovy
src/com/ft/jenkins/git/GitUtils.groovy
test-src/com/ft/jenkins/BasePipelineUnitTest.groovy
vars/genericEntryPointForJenkinsfile.groovy

Fixes https://github.com/Financial-Times/k8s-pipeline-library/issues/95
Will deploy in team envs on simple tags

Allow no GitHub prerelease

---

src/com/ft/jenkins/changerequests/ChangeRequestOpenData.groovy
src/com/ft/jenkins/changerequests/ChangeRequestsUtils.groovy
src/com/ft/jenkins/provision/ProvisionerUtil.groovy
vars/upperEnvsBuildAndDeploy.groovy

Tested by doing a CoreOS upgrade and by re-deploying a helm chart.

Change system code

---

Pipeline_integration_points.md
src/com/ft/jenkins/changerequests/ChangeRequestPopulateSystemCode.groovy
vars/upperEnvsBuildAndDeploy.groovy

* Add Helm Chart name to Biz-Ops systemCode mapping
* Fixing variable names
* Fixing variable double quotes
* Change to GraphQL API
* Change to GraphQL API fix1
* Change to GraphQL API fix2
* Change to GraphQL API fix3
* Change to GraphQL API fix4
* Change to GraphQL API fix5
* Change to GraphQL API fix6
* Change to GraphQL API fix7

Feature/cph 84 add system code map (#112)

---

src/com/ft/jenkins/EnvsRegistry.groovy

To be merged just before the start of DEV clusters re provisioning

Set K8S DEV clusters to UPP.FT.COM

---

src/com/ft/jenkins/git/GitUtils.groovy
vars/genericEntryPointForJenkinsfile.groovy

Change from parsing branches to tags to directly using tags.

Cph 117 testing tags

---

src/com/ft/jenkins/EnvsRegistry.groovy

Reverts Financial-Times/k8s-pipeline-library#129

Revert "To use for pac pipeline"

---

src/com/ft/jenkins/EnvsRegistry.groovy

Reverts Financial-Times/k8s-pipeline-library#128

Revert "Update staging URLs"

---

Pipeline_integration_points.md
src/com/ft/jenkins/changerequests/ChangeRequestPopulateSystemCode.groovy
vars/upperEnvsBuildAndDeploy.groovy

Going to auto-deploy-stable with new CR changes.

---

src/com/ft/jenkins/cluster/Clusters.groovy

Add record for publish dev cluster

---

src/com/ft/jenkins/cluster/Clusters.groovy

Update pac-staging-eu map to switch to an EKS based K8S cluster.
___

Update pac-staging-eu map

---

src/com/ft/jenkins/cluster/Clusters.groovy

Add configs in prepartion for eks-publish-staging-eu

---

src/com/ft/jenkins/appconfigs/AppConfigs.groovy
src/com/ft/jenkins/deployment/Deployments.groovy
test-src/com/ft/jenkins/appconfigs/AppConfigsSpec.groovy
test-src/com/ft/jenkins/cluster/EnvRegistrySpec.groovy

UPPSF-1555 Fixed app config filtering when a deploy region is specified

---

src/com/ft/jenkins/cluster/Clusters.groovy

Change API endpoint of eks-delivery-staging-eu

---

src/com/ft/jenkins/cluster/Clusters.groovy

Change API endtpoint  for pac-prod-us

---

src/com/ft/jenkins/cluster/Clusters.groovy

Change pac-prod-eu cluster api

---

src/com/ft/jenkins/cluster/Clusters.groovy

- [ X] Minor change (e.g. fixing a typo, adding config)
___

Change API endpoint of new provisioned publish dev

---

src/com/ft/jenkins/cluster/Clusters.groovy

New API endpoint for eks-publish-dev-eu

---

src/com/ft/jenkins/cluster/Clusters.groovy

Change API endpoint for eks-delivery-dev-eu

---

src/com/ft/jenkins/cluster/Clusters.groovy

Change API for eks-pac-staging-eu

---

src/com/ft/jenkins/cluster/Clusters.groovy

Change API of eks-delivery-staging-us

---

src/com/ft/jenkins/cluster/Clusters.groovy

Change API of eks-delivery-staging-eu

---

src/com/ft/jenkins/cluster/Clusters.groovy

Change API for eks-pac-prod-us

---

src/com/ft/jenkins/cluster/Clusters.groovy

Change api for cluster eks-pac-prod-eu

---

src/com/ft/jenkins/cluster/Clusters.groovy

Change API for eks-publish-prod-eu

---

src/com/ft/jenkins/cluster/Clusters.groovy

Change API eks-delivery-prod-eu

---

src/com/ft/jenkins/cluster/Clusters.groovy

Change API for eks-delivery-prod-us

---

src/com/ft/jenkins/cluster/Clusters.groovy

Change API endpoint for eks-publish-dev-eu
